# -*- coding: utf-8 -*-
"""heatmap_criminalidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MrRnSaHJuUxAoY5-MC3pT-JOjnvEIoE
"""

import streamlit as st
import pandas as pd
import folium
from folium.plugins import HeatMap
from streamlit_folium import st_folium
import requests
import zipfile
import io

st.set_page_config(page_title="Heatmap Criminalidade Juazeiro", layout="wide")

st.title("Mapa de Criminalidade – Juazeiro/BA")

# URL do ZIP no GitHub
GITHUB_ZIP_URL = "https://raw.githubusercontent.com/uirasiqueira/heatmap_crime_juazeiro/main/raw.zip"

@st.cache_data
def load_data():
    try:
        # 1. Baixar ZIP
        response = requests.get(GITHUB_ZIP_URL)
        response.raise_for_status()

        # 2. Abrir ZIP em memória
        zip_file = zipfile.ZipFile(io.BytesIO(response.content))

        # 3. Pegar o único CSV dentro do ZIP
        csv_name = zip_file.namelist()[0]

        # 4. Ler CSV
        df = pd.read_csv(zip_file.open(csv_name), encoding="latin1")

        # -------------------------
        # NORMALIZAÇÃO DA TABELA
        # -------------------------
        df.columns = (
            df.columns
            .str.strip()
            .str.replace('\ufeff', '')  # remove BOM
            .str.upper()
        )

        # Garantir que as colunas existem
        if "LATITUDE" not in df.columns or "LONGITUDE" not in df.columns:
            raise ValueError("O arquivo não possui LATITUDE e LONGITUDE após normalização.")

        # Corrigir vírgulas → ponto
        df["LATITUDE"] = df["LATITUDE"].astype(str).str.replace(",", ".")
        df["LONGITUDE"] = df["LONGITUDE"].astype(str).str.replace(",", ".")

        # Converter para float
        df["LATITUDE"] = pd.to_numeric(df["LATITUDE"], errors="coerce")
        df["LONGITUDE"] = pd.to_numeric(df["LONGITUDE"], errors="coerce")

        # Remover coordenadas inválidas
        df = df.dropna(subset=["LATITUDE", "LONGITUDE"])

        return df

    except Exception as e:
        st.error(f"Erro ao carregar CSV: {e}")
        return None


df = load_data()

if df is not None and not df.empty:
    st.success("Dados carregados com sucesso!")

    # -------------------------
    # MAPA
    # -------------------------
    m = folium.Map(location=[-9.4167, -40.5033], zoom_start=12)

    heat_data = df[["LATITUDE", "LONGITUDE"]].values.tolist()
    HeatMap(heat_data, radius=10).add_to(m)

    st_folium(m, width=900, height=600)

else:
    st.warning("Nenhum dado carregado.")
