# -*- coding: utf-8 -*-
"""heatmap_criminalidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MrRnSaHJuUxAoY5-MC3pT-JOjnvEIoE
"""

import streamlit as st
import pandas as pd
import folium
from folium.plugins import HeatMap
from streamlit_folium import st_folium
import requests
import zipfile
import io

st.set_page_config(page_title="Heatmap Criminalidade Juazeiro", layout="wide")

st.title("Mapa de Criminalidade – Juazeiro/BA")

# URL do ZIP no GitHub
GITHUB_ZIP_URL = "https://raw.githubusercontent.com/uirasiqueira/heatmap_crime_juazeiro/main/raw.zip"

@st.cache_data
def load_data():
    try:
        # 1. Baixar ZIP
        response = requests.get(GITHUB_ZIP_URL)
        response.raise_for_status()

        # 2. Abrir ZIP em memória
        zip_file = zipfile.ZipFile(io.BytesIO(response.content))

        # 3. Pegar o único CSV dentro do ZIP
        csv_name = zip_file.namelist()[0]

        # 4. Ler CSV
        df = pd.read_csv(zip_file.open(csv_name), encoding="latin1")

        # -------------------------
        # NORMALIZAÇÃO DA TABELA
        # -------------------------
        df.columns = (
            df.columns
            .str.strip()
            .str.replace('\ufeff', '')  # remove BOM
            .str.upper()
        )

        # Garantir que as colunas existem
        if "LATITUDE" not in df.columns or "LONGITUDE" not in df.columns:
            raise ValueError("O arquivo não possui LATITUDE e LONGITUDE após normalização.")

        # Corrigir vírgulas → ponto
        df["LATITUDE"] = df["LATITUDE"].astype(str).str.replace(",", ".")
        df["LONGITUDE"] = df["LONGITUDE"].astype(str).str.replace(",", ".")

        # Converter para float
        df["LATITUDE"] = pd.to_numeric(df["LATITUDE"], errors="coerce")
        df["LONGITUDE"] = pd.to_numeric(df["LONGITUDE"], errors="coerce")

       # Filtrar Juazeiro-BA
        df_juazeiro = df[df['MUNICIPIO FATO'].str.contains('Juazeiro', case=False, na=False)]

        # Remover linhas sem coordenadas
        df_juazeiro = df_juazeiro.dropna(subset=['LATITUDE', 'LONGITUDE'])

        return df_juazeiro
    except Exception as e:
        st.error(f"Erro ao carregar CSV: {e}")
        return pd.DataFrame()

# Carregar dados
df_juazeiro = load_data(GITHUB_URL)

# Preview dos dados
if df_juazeiro.empty:
    st.stop()
else:
    st.subheader("Preview dos dados filtrados")
    st.dataframe(df_juazeiro.head())

# =========================
# Criar mapa
# =========================
mapa = folium.Map(
    location=[df_juazeiro['LATITUDE'].mean(), df_juazeiro['LONGITUDE'].mean()],
    zoom_start=12
)

# Criar HeatMap mais escuro e intenso
heat_data = df_juazeiro[['LATITUDE', 'LONGITUDE']].values.tolist()

HeatMap(
    heat_data,
    radius=18,          # aumenta o tamanho dos pontos
    blur=12,            # deixa mais definido
    max_zoom=1,         # intensifica contraste
    min_opacity=0.5,    # aumenta visibilidade
).add_to(mapa)

# Exibir mapa no Streamlit
st.subheader("Mapa de Crimes - HeatMap (Intenso)")
st_folium(mapa, width=900, height=600)
