# -*- coding: utf-8 -*-
"""heatmap_criminalidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MrRnSaHJuUxAoY5-MC3pT-JOjnvEIoE
"""

import streamlit as st
import pandas as pd
import folium
from folium.plugins import HeatMap
from streamlit_folium import st_folium

# =========================
# Configurações do Streamlit
# =========================
st.set_page_config(layout="wide")
st.title("Mapa de Crimes de Juazeiro")
st.markdown("Visualize a localização dos crimes na cidade em um mapa interativo.")

# =========================
# CSV no GitHub
# =========================
GITHUB_URL = "https://github.com/uirasiqueira/heatmap_crime_juazeiro/blob/main/raw.csv"

# =========================
# Função para carregar dados
# =========================
@st.cache_data
def load_data(url):
    try:
        # Lê o CSV, ignorando linhas problemáticas
        df = pd.read_csv(url, encoding='utf-8-sig', on_bad_lines='skip')

        # Normaliza nomes das colunas: remove espaços e coloca tudo em maiúsculo
        df.columns = df.columns.str.strip().str.upper()

        # Corrigir LATITUDE e LONGITUDE
        df['LATITUDE'] = pd.to_numeric(df['LATITUDE'].astype(str).str.replace(',', '.'), errors='coerce')
        df['LONGITUDE'] = pd.to_numeric(df['LONGITUDE'].astype(str).str.replace(',', '.'), errors='coerce')

        # Filtrar Juazeiro-BA
        df_juazeiro = df[df['MUNICIPIO FATO'].str.contains('Juazeiro', case=False, na=False)]

        # Remover linhas sem coordenadas
        df_juazeiro = df_juazeiro.dropna(subset=['LATITUDE', 'LONGITUDE'])

        return df_juazeiro

    except Exception as e:
        st.error(f"Erro ao carregar CSV: {e}")
        return pd.DataFrame()


# Carregar dados
df_juazeiro = load_data(GITHUB_URL)

# Preview dos dados
if df_juazeiro.empty:
    st.stop()
else:
    st.subheader("Preview dos dados filtrados")
    st.dataframe(df_juazeiro.head())

# =========================
# Criar mapa
# =========================
mapa = folium.Map(
    location=[df_juazeiro['LATITUDE'].mean(), df_juazeiro['LONGITUDE'].mean()],
    zoom_start=12
)

# Adicionar HeatMap
heat_data = df_juazeiro[['LATITUDE', 'LONGITUDE']].values.tolist()
HeatMap(heat_data).add_to(mapa)

# Exibir mapa no Streamlit
st.subheader("Mapa de Crimes - HeatMap")
st_folium(mapa, width=800, height=600)

